generated: '2026-08-26T12:23:57.961221'
shoulder_pan:
  range_min: 714
  range_max: 3429
  homing_offset: 2071
shoulder_lift:
  range_min: 864
  range_max: 3251
  homing_offset: 2057
elbow_flex:
  range_min: 869
  range_max: 3074
  homing_offset: 1971
wrist_flex:
  range_min: 846
  range_max: 3179
  homing_offset: 2012
wrist_roll:
  range_min: 210
  range_max: 4006
  homing_offset: 2108
gripper:
  range_min: 1521
  range_max: 2966
  homing_offset: 2243
