generated: '2026-08-26T12:18:25.206951'
shoulder_pan:
  range_min: 714
  range_max: 3419
  homing_offset: 2066
shoulder_lift:
  range_min: 842
  range_max: 3147
  homing_offset: 1994
elbow_flex:
  range_min: 909
  range_max: 3120
  homing_offset: 2014
wrist_flex:
  range_min: 988
  range_max: 3236
  homing_offset: 2112
wrist_roll:
  range_min: 252
  range_max: 3986
  homing_offset: 2119
gripper:
  range_min: 1708
  range_max: 3163
  homing_offset: 2435
